import { mkdir, writeFile } from 'node:fs/promises';
import { collectAll, createAdapters } from '@hot-topics/adapters';
import type { PlatformContribution, RawHotItem, Region, SourceCategory } from '@hot-topics/core';
import { assignToExistingTopics } from '@hot-topics/clustering';
import { computeHeat, normalizePlatformItems } from '@hot-topics/scoring';
import { clamp, nowIso, slugify, stableHash } from '@hot-topics/shared';
import { applyQualityGate } from '../workers/pipeline/src/quality.ts';

const retrievedAt=nowIso();const runId=`smoke_${retrievedAt.replace(/[-:.TZ]/g,'').slice(0,12)}`;const env=process.env as Record<string,string|undefined>;
const adapters=createAdapters(env);const results=await collectAll(adapters,{runId,retrievedAt,env});
const accepted:RawHotItem[]=[];const sourceReports=[] as Array<Record<string,unknown>>;
for(const r of results){const gated=(r.status==='healthy'||r.status==='degraded')?applyQualityGate(r.adapter,r.items):{accepted:[] as RawHotItem[],status:r.status,warnings:[]};accepted.push(...gated.accepted.slice(0,30));sourceReports.push({source:r.adapter.id,region:r.adapter.region,status:r.status,item_count:gated.accepted.length,duration_ms:r.durationMs,warnings:gated.warnings,error:r.error});}
const seeds:Array<{topicId:string;title:string;firstSeenAt:string;lastSeenAt:string}>=[];const groups=new Map<string,RawHotItem[]>();
for(const item of accepted){const [assignment]=await assignToExistingTopics([item],seeds);let topicId=assignment?.topicId;if(!topicId){topicId=`topic_${stableHash(`${item.title}|${retrievedAt.slice(0,10)}`)}`;seeds.push({topicId,title:item.title,firstSeenAt:retrievedAt,lastSeenAt:retrievedAt});}const arr=groups.get(topicId)??[];arr.push(item);groups.set(topicId,arr);}
const bySource=new Map<string,RawHotItem[]>();for(const item of accepted){const a=bySource.get(item.sourceId)??[];a.push(item);bySource.set(item.sourceId,a);}const itemScore=new Map<string,number>();for(const [source,items] of bySource){normalizePlatformItems(items).forEach((v,i)=>itemScore.set(`${source}:${items[i]!.id}`,v));}
const rankings:Array<Record<string,unknown>>=[];for(const [topicId,items] of groups){for(const region of ['CN','GLOBAL'] as Region[]){const subset=items.filter((x)=>x.region===region);if(!subset.length)continue;const sourceMap=new Map<string,RawHotItem[]>();for(const item of subset){const a=sourceMap.get(item.sourceId)??[];a.push(item);sourceMap.set(item.sourceId,a);}const contributions:PlatformContribution[]=[];for(const [sourceId,rows] of sourceMap){const category=rows[0]!.sourceType as SourceCategory;const ph=Math.max(...rows.map((x)=>itemScore.get(`${sourceId}:${x.id}`)??0));const raw=Math.max(...rows.map((x)=>(x.views??0)+3*(x.comments??0)+(x.rawHeat??0)));contributions.push({sourceId,sourceCategory:category,region,platformHeat:ph,reliabilityWeight:Number(rows[0]!.sourceMetadata?.reliabilityWeight??1),rawVolumeSignal:raw?clamp(20*Math.log10(1+raw)):ph,searchSignal:category==='search'?ph:0});}const score=computeHeat(contributions,{persistence:35,freshness:100});rankings.push({topic_id:topicId,region,title:items[0]!.title,slug:slugify(items[0]!.title),heat:score.heat,components:score.components,cross_platform_index:score.crossPlatformIndex,coverage_confidence:score.coverageConfidence,sources:[...sourceMap.keys()]});}}
rankings.sort((a,b)=>Number(b.heat)-Number(a.heat));const workingCN=sourceReports.filter((x)=>x.region==='CN'&&['healthy','degraded'].includes(String(x.status))&&Number(x.item_count)>=3).length;const workingGlobal=sourceReports.filter((x)=>x.region==='GLOBAL'&&['healthy','degraded'].includes(String(x.status))&&Number(x.item_count)>=3).length;
const report={run_id:runId,retrieved_at:retrievedAt,real_data:accepted.length>0,china_sources_working:workingCN,global_sources_working:workingGlobal,raw_item_count:accepted.length,topic_count:groups.size,pipeline_verified:accepted.length>0&&groups.size>0,sources:sourceReports,top5:rankings.slice(0,5)};
await mkdir('artifacts',{recursive:true});await writeFile('artifacts/real_pipeline_report.json',JSON.stringify(report,null,2)+'\n');process.stdout.write(`${JSON.stringify(report,null,2)}\n`);if(!report.pipeline_verified)process.exit(2);
